### ISSUE TITLE
Some of the configs not written to .weerc

### ISSUE THREAD

**Issue by kutsan** [klloe/weechat-autoconf#1]
For example some colors and `weechat.bar.buffers.size`, `weechat.bar.buffers.size_max`. Since a lot of configs going on I can't exactly estimate what specific configs not written yet.

My `weechat.bar.buffers.size` config is set to 25 but even `iset` says it's default but I know it's not. What's the problem?

By the way, thanks for writing this out.

**Comment by klloe** [comment]
Hey,

thanks for your fast response and trying out ma script 😹 

would you mind to share your `weerc` file and the toutput of `/set diff`?

It may have to do with the regex matcher (some options may not use 2 spaces at the end).

**Comment by kutsan** [comment]
Actually, seems like it's not your fault. See https://github.com/weechat/weechat/issues/846. I can't even see `weechat.bar.*` option to there. Sorry for bother you. 😅

**Comment by klloe** [comment]
No problem, I'm very lucky with someone is testing my script!

**Comment by kutsan** [comment]
Hehe. I tested on a Mac and Ubuntu Server machine, if you wanted to know. It works flawlessly. But I am still dreaming to share one readable and sharable file to apply all of my configs without thinking anything. With your script, we still need to install plugins; otherwise they don't automatically install themselves, but I guess it's beyond weechat's API capabilities. And other options who forget its default values are problem.

**Comment by klloe** [comment]
@kutsan Thanks you mention this! I already planned that feature for the next version (even including custom keybindings). I just released this one first so I stay motivated enough and keep going. I also want to create a more readable output with sections and if possible to not truncate the file all the time. 

I don't know about the missing defaults of bars yet, but maybe some of them will be gone with the release of weechat 1.8 including a new buflist feature (replaces buffers.pl).

**Comment by kutsan** [comment]
@klloe It's approved, congrats. You may want to edit the README. Sorry, if you saw earlier. Just wanted to inform you.

**Comment by klloe** [comment]
@kutsan Thanks, you still seem to use the script even if it has its issues!

**Comment by kutsan** [comment]
Of course. Because, I dig it that much. I still find magical, against WeeChat's bunch of configs.
